import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const rituals = [
  {
    slug: 'diwali-lakshmi-puja',
    name: 'Diwali Lakshmi Puja',
    nameHi: 'दीवाली लक्ष्मी पूजा',
    description: 'Worship of Goddess Lakshmi on the night of Diwali for prosperity and wealth.',
    category: 'festival',
    tradition: 'north',
    isFree: true,
    durationMinutes: 60,
    steps: [
      { order: 1, title: 'Purification', titleHi: 'शुद्धिकरण', description: 'Clean the puja area and take a bath.', descHi: 'पूजा स्थान को साफ करें और स्नान करें।' },
      { order: 2, title: 'Kalash Sthapana', titleHi: 'कलश स्थापना', description: 'Place a copper pot filled with water, mango leaves and coconut on the altar.', descHi: 'तांबे का कलश जल, आम के पत्ते और नारियल से भरकर वेदी पर रखें।' },
      { order: 3, title: 'Ganesh Puja', titleHi: 'गणेश पूजा', description: 'Invoke Lord Ganesha first to remove obstacles.', descHi: 'सबसे पहले विघ्न हर्ता गणेश जी का पूजन करें।' },
      { order: 4, title: 'Lakshmi Avahan', titleHi: 'लक्ष्मी आवाहन', description: 'Invoke Goddess Lakshmi with the mantra "Om Shreem Mahalakshmiyei Namah".', descHi: '"ॐ श्रीं महालक्ष्म्यै नमः" मंत्र से माँ लक्ष्मी का आवाहन करें।' },
      { order: 5, title: 'Shodashopachara', titleHi: 'षोडशोपचार', description: 'Offer 16 services: seat, water for feet, water for hands, water, bathing, clothing, sacred thread, perfume, flowers, incense, lamp, food, betel nut, circumambulation, obeisance, and farewell.', descHi: '16 उपचार अर्पित करें: आसन, पाद्य, अर्घ्य, आचमन, स्नान, वस्त्र, यज्ञोपवीत, गंध, पुष्प, धूप, दीप, नैवेद्य, ताम्बूल, परिक्रमा, नमस्कार और विसर्जन।' },
      { order: 6, title: 'Aarti', titleHi: 'आरती', description: 'Perform Lakshmi Aarti with camphor and ghee lamps.', descHi: 'कपूर और घी के दीपों से लक्ष्मी आरती करें।' },
    ],
    samagri: [
      { name: 'Copper Kalash', nameHi: 'तांबे का कलश', quantity: '1' },
      { name: 'Mango leaves', nameHi: 'आम के पत्ते', quantity: '11' },
      { name: 'Coconut', nameHi: 'नारियल', quantity: '1' },
      { name: 'Rice', nameHi: 'चावल', quantity: '250g' },
      { name: 'Red cloth', nameHi: 'लाल वस्त्र', quantity: '1' },
      { name: 'Kumkum', nameHi: 'कुमकुम', quantity: '1 packet' },
      { name: 'Turmeric', nameHi: 'हल्दी', quantity: '50g' },
      { name: 'Ghee', nameHi: 'घी', quantity: '100g' },
      { name: 'Camphor', nameHi: 'कपूर', quantity: '10g' },
      { name: 'Incense sticks', nameHi: 'अगरबत्ती', quantity: '1 pack' },
      { name: 'Lotus flowers', nameHi: 'कमल के फूल', quantity: '5', optional: true },
      { name: 'Sweets', nameHi: 'मिठाई', quantity: '500g' },
    ],
  },
  {
    slug: 'ganesh-chaturthi-puja',
    name: 'Ganesh Chaturthi Puja',
    nameHi: 'गणेश चतुर्थी पूजा',
    description: 'Celebration of Lord Ganesha\'s birth with elaborate worship and modak offerings.',
    category: 'festival',
    tradition: 'south',
    isFree: true,
    durationMinutes: 90,
    steps: [
      { order: 1, title: 'Idol Installation', titleHi: 'मूर्ति स्थापना', description: 'Place Ganesha idol facing north or east on a raised platform decorated with flowers.', descHi: 'गणेश मूर्ति को फूलों से सजे ऊंचे मंच पर उत्तर या पूर्व की ओर मुख करके स्थापित करें।' },
      { order: 2, title: 'Prana Pratishtha', titleHi: 'प्राण प्रतिष्ठा', description: 'Invoke the divine presence into the idol with Vedic mantras.', descHi: 'वैदिक मंत्रों से मूर्ति में दिव्य उपस्थिति का आवाहन करें।' },
      { order: 3, title: 'Shodashopachar Puja', titleHi: 'षोडशोपचार पूजा', description: 'Offer 16 services to Lord Ganesha.', descHi: 'भगवान गणेश को 16 उपचार अर्पित करें।' },
      { order: 4, title: 'Modak Offering', titleHi: 'मोदक अर्पण', description: 'Offer 21 modaks — Lord Ganesha\'s favourite sweet.', descHi: '21 मोदक अर्पित करें — गणेश जी का प्रिय मिष्टान्न।' },
      { order: 5, title: 'Aarti and Prasad', titleHi: 'आरती और प्रसाद', description: 'Perform Ganesha Aarti and distribute prasad.', descHi: 'गणेश आरती करें और प्रसाद वितरित करें।' },
    ],
    samagri: [
      { name: 'Ganesha idol (clay)', nameHi: 'मिट्टी की गणेश मूर्ति', quantity: '1' },
      { name: 'Modak', nameHi: 'मोदक', quantity: '21' },
      { name: 'Red flowers', nameHi: 'लाल फूल', quantity: '108' },
      { name: 'Durva grass', nameHi: 'दूर्वा घास', quantity: '21 bunches' },
      { name: 'Coconut', nameHi: 'नारियल', quantity: '2' },
      { name: 'Betel leaves', nameHi: 'पान के पत्ते', quantity: '11' },
      { name: 'Incense sticks', nameHi: 'अगरबत्ती', quantity: '1 pack' },
    ],
  },
  {
    slug: 'navratri-vrat',
    name: 'Navratri Vrat',
    nameHi: 'नवरात्रि व्रत',
    description: 'Nine nights of fasting and worship of Goddess Durga in her nine forms.',
    category: 'festival',
    tradition: 'north',
    isFree: false,
    durationMinutes: 45,
    steps: [
      { order: 1, title: 'Ghatasthapana', titleHi: 'घटस्थापना', description: 'Establish the sacred pot on the first day with barley seeds for sprouting.', descHi: 'पहले दिन जौ के बीज अंकुरण के लिए पवित्र घट स्थापित करें।' },
      { order: 2, title: 'Daily Puja', titleHi: 'दैनिक पूजा', description: 'Worship each of the nine forms of Durga on successive days.', descHi: 'क्रमशः नौ दिनों में दुर्गा के नौ रूपों की पूजा करें।' },
      { order: 3, title: 'Akhanda Jyoti', titleHi: 'अखंड ज्योति', description: 'Keep an uninterrupted flame burning throughout the nine days.', descHi: 'नौ दिनों तक अखंड ज्योति जलाए रखें।' },
      { order: 4, title: 'Kanya Puja', titleHi: 'कन्या पूजा', description: 'On Ashtami or Navami, worship nine young girls as manifestations of the Devi.', descHi: 'अष्टमी या नवमी पर नौ बालिकाओं को देवी स्वरूप मानकर पूजन करें।' },
    ],
    samagri: [
      { name: 'Earthen pot (kalash)', nameHi: 'मिट्टी का कलश', quantity: '1' },
      { name: 'Barley seeds', nameHi: 'जौ के बीज', quantity: '100g' },
      { name: 'Sand/soil', nameHi: 'रेत/मिट्टी', quantity: '1 tray' },
      { name: 'Red chunri', nameHi: 'लाल चुनरी', quantity: '1' },
      { name: 'Coconut with leaves', nameHi: 'सपत्र नारियल', quantity: '1' },
      { name: 'Oil lamp', nameHi: 'तेल का दीपक', quantity: '1' },
    ],
  },
  {
    slug: 'onam-puja',
    name: 'Onam Puja',
    nameHi: null,
    description: 'Harvest festival celebrating King Mahabali\'s annual return to Kerala.',
    category: 'festival',
    tradition: 'south',
    isFree: false,
    durationMinutes: 30,
    steps: [
      { order: 1, title: 'Pookalam', titleHi: null, description: 'Create an elaborate flower carpet (pookalam) in front of the home.', descHi: null },
      { order: 2, title: 'Thrikkakara Appan', titleHi: null, description: 'Install the clay idol of Vamana in the center of the pookalam.', descHi: null },
      { order: 3, title: 'Puja', titleHi: null, description: 'Perform puja with flowers, lamps, and incense.', descHi: null },
      { order: 4, title: 'Onam Sadhya', titleHi: null, description: 'Prepare and share the grand Onam feast on banana leaves.', descHi: null },
    ],
    samagri: [
      { name: 'Assorted flowers', nameHi: null, quantity: 'multiple varieties' },
      { name: 'Clay Vamana idol', nameHi: null, quantity: '1' },
      { name: 'Banana leaves', nameHi: 'केले के पत्ते', quantity: '10' },
      { name: 'Oil lamp', nameHi: 'तेल का दीपक', quantity: '1' },
    ],
  },
  {
    slug: 'vivah-sanskar',
    name: 'Vivah Sanskar',
    nameHi: 'विवाह संस्कार',
    description: 'Sacred Hindu wedding ceremony uniting two souls with Vedic rites.',
    category: 'lifecycle',
    tradition: 'north',
    isFree: true,
    durationMinutes: 180,
    steps: [
      { order: 1, title: 'Ganesh Puja', titleHi: 'गणेश पूजा', description: 'Begin with Ganesha worship to bless the ceremony.', descHi: 'समारोह को आशीर्वाद के लिए गणेश पूजा से प्रारंभ करें।' },
      { order: 2, title: 'Var Puja', titleHi: 'वर पूजा', description: 'Bride\'s family welcomes and worships the groom.', descHi: 'वधू पक्ष द्वारा वर का स्वागत और पूजन।' },
      { order: 3, title: 'Kanyadan', titleHi: 'कन्यादान', description: 'Father gives the bride\'s hand to the groom — the most sacred act.', descHi: 'पिता द्वारा वर के हाथ में कन्या का हाथ देना — सबसे पवित्र कार्य।' },
      { order: 4, title: 'Vivah Homa', titleHi: 'विवाह होम', description: 'Sacred fire is lit and mantras are chanted.', descHi: 'पवित्र अग्नि प्रज्वलित की जाती है और मंत्रों का उच्चारण होता है।' },
      { order: 5, title: 'Saptapadi', titleHi: 'सप्तपदी', description: 'Bride and groom take seven steps together around the sacred fire making seven vows.', descHi: 'वर-वधू पवित्र अग्नि के चारों ओर सात फेरे लेते हुए सात प्रतिज्ञाएँ करते हैं।' },
      { order: 6, title: 'Sindoor and Mangalsutra', titleHi: 'सिंदूर और मंगलसूत्र', description: 'Groom applies sindoor in the bride\'s hair parting and ties the mangalsutra.', descHi: 'वर वधू की माँग में सिंदूर लगाता है और मंगलसूत्र बांधता है।' },
    ],
    samagri: [
      { name: 'Havan kund', nameHi: 'हवन कुंड', quantity: '1' },
      { name: 'Ghee', nameHi: 'घी', quantity: '1kg' },
      { name: 'Samagri (havan mix)', nameHi: 'हवन सामग्री', quantity: '500g' },
      { name: 'Sindoor', nameHi: 'सिंदूर', quantity: '1 packet' },
      { name: 'Mangalsutra', nameHi: 'मंगलसूत्र', quantity: '1' },
      { name: 'Yellow cloth (2 pieces)', nameHi: 'पीला वस्त्र', quantity: '2 pieces' },
      { name: 'Betel nuts', nameHi: 'सुपारी', quantity: '21' },
    ],
  },
  {
    slug: 'namakarana',
    name: 'Namakarana',
    nameHi: 'नामकरण',
    description: 'Naming ceremony for a newborn, traditionally performed on the 11th day.',
    category: 'lifecycle',
    tradition: 'south',
    isFree: true,
    durationMinutes: 45,
    steps: [
      { order: 1, title: 'Purification', titleHi: 'शुद्धिकरण', description: 'Purify the mother, child and puja area.', descHi: 'माँ, शिशु और पूजा स्थान का शुद्धिकरण करें।' },
      { order: 2, title: 'Navagraha Puja', titleHi: 'नवग्रह पूजा', description: 'Worship nine planets for child\'s protection and blessings.', descHi: 'शिशु की सुरक्षा और आशीर्वाद के लिए नवग्रह पूजा करें।' },
      { order: 3, title: 'Name Announcement', titleHi: 'नाम घोषणा', description: 'Father whispers the chosen name into the baby\'s right ear.', descHi: 'पिता शिशु के दाहिने कान में चयनित नाम फुसफुसाते हैं।' },
      { order: 4, title: 'Blessings', titleHi: 'आशीर्वाद', description: 'Elders bless the child with gold, rice, and mantras.', descHi: 'बड़े-बुजुर्ग सोने, चावल और मंत्रों से शिशु को आशीर्वाद देते हैं।' },
    ],
    samagri: [
      { name: 'Gold coin or ring', nameHi: 'सोने का सिक्का या अंगूठी', quantity: '1', optional: true },
      { name: 'Rice', nameHi: 'चावल', quantity: '100g' },
      { name: 'Honey', nameHi: 'शहद', quantity: '50ml' },
      { name: 'Ghee', nameHi: 'घी', quantity: '50ml' },
      { name: 'Incense sticks', nameHi: 'अगरबत्ती', quantity: '1 pack' },
    ],
  },
  {
    slug: 'annaprashan',
    name: 'Annaprashan',
    nameHi: 'अन्नप्राशन',
    description: 'First solid food ceremony for an infant, typically at 6 months for boys and 5 or 7 months for girls.',
    category: 'lifecycle',
    tradition: 'east',
    isFree: false,
    durationMinutes: 60,
    steps: [
      { order: 1, title: 'Mangalacharana', titleHi: 'मंगलाचरण', description: 'Chant auspicious mantras to begin the ceremony.', descHi: 'समारोह प्रारंभ करने के लिए मंगलाचरण मंत्रों का पाठ करें।' },
      { order: 2, title: 'Navagraha Puja', titleHi: 'नवग्रह पूजा', description: 'Worship nine planets for the child\'s wellbeing.', descHi: 'बच्चे की भलाई के लिए नवग्रह पूजा करें।' },
      { order: 3, title: 'First Feeding', titleHi: 'प्रथम अन्नदान', description: 'Father feeds the first morsel of kheer (rice pudding) to the child.', descHi: 'पिता बच्चे को खीर (चावल की खीर) का पहला कौर खिलाते हैं।' },
      { order: 4, title: 'Choice Prediction', titleHi: 'भविष्य निर्धारण', description: 'Place objects (book, soil, food, money) before the child — the first item chosen predicts their vocation.', descHi: 'बच्चे के सामने वस्तुएं रखें (पुस्तक, मिट्टी, भोजन, धन) — पहली चुनी वस्तु उनके भविष्य का संकेत देती है।' },
    ],
    samagri: [
      { name: 'Rice', nameHi: 'चावल', quantity: '250g' },
      { name: 'Milk', nameHi: 'दूध', quantity: '500ml' },
      { name: 'Sugar/Jaggery', nameHi: 'चीनी/गुड़', quantity: '100g' },
      { name: 'Silver bowl and spoon', nameHi: 'चांदी की कटोरी और चम्मच', quantity: '1 set', optional: true },
      { name: 'New clothes for baby', nameHi: 'बच्चे के लिए नए वस्त्र', quantity: '1 set' },
    ],
  },
  {
    slug: 'somvati-amavasya',
    name: 'Somvati Amavasya',
    nameHi: 'सोमवती अमावस्या',
    description: 'New moon falling on a Monday — specially sacred for ancestral rites and Shiva worship.',
    category: 'monthly',
    tradition: 'north',
    isFree: true,
    durationMinutes: 30,
    steps: [
      { order: 1, title: 'Early Bath', titleHi: 'प्रातःस्नान', description: 'Take a bath in a sacred river or at home before sunrise.', descHi: 'सूर्योदय से पहले पवित्र नदी में या घर पर स्नान करें।' },
      { order: 2, title: 'Peepal Tree Puja', titleHi: 'पीपल वृक्ष पूजा', description: 'Circumambulate the Peepal tree 108 times offering water and red thread.', descHi: 'पीपल के वृक्ष को जल और लाल धागा अर्पित करते हुए 108 परिक्रमा करें।' },
      { order: 3, title: 'Pitru Tarpan', titleHi: 'पितृ तर्पण', description: 'Offer sesame seeds and water to ancestors.', descHi: 'पितरों को तिल और जल से तर्पण करें।' },
      { order: 4, title: 'Shiva Puja', titleHi: 'शिव पूजा', description: 'Offer bilva leaves and milk to Shiva Linga.', descHi: 'शिवलिंग पर बेलपत्र और दूध अर्पित करें।' },
    ],
    samagri: [
      { name: 'Sesame seeds (black)', nameHi: 'काला तिल', quantity: '100g' },
      { name: 'Red thread', nameHi: 'लाल धागा', quantity: '1 roll' },
      { name: 'Bilva leaves', nameHi: 'बेलपत्र', quantity: '21' },
      { name: 'Milk', nameHi: 'दूध', quantity: '500ml' },
      { name: 'Flowers', nameHi: 'फूल', quantity: '1 bunch' },
    ],
  },
  {
    slug: 'ekadashi-vrat',
    name: 'Ekadashi Vrat',
    nameHi: 'एकादशी व्रत',
    description: 'Fasting on the eleventh day of each lunar fortnight, sacred to Lord Vishnu.',
    category: 'monthly',
    tradition: 'north',
    isFree: true,
    durationMinutes: 20,
    steps: [
      { order: 1, title: 'Sankalpa', titleHi: 'संकल्प', description: 'Take a vow of fasting on Dashami (tenth day) evening.', descHi: 'दशमी की संध्या को व्रत का संकल्प लें।' },
      { order: 2, title: 'Morning Puja', titleHi: 'प्रातः पूजा', description: 'Worship Lord Vishnu with tulsi leaves, flowers, and Vishnu Sahasranama.', descHi: 'तुलसी, फूलों और विष्णु सहस्रनाम से भगवान विष्णु का पूजन करें।' },
      { order: 3, title: 'Fasting', titleHi: 'उपवास', description: 'Observe a partial or complete fast throughout the day.', descHi: 'पूरे दिन आंशिक या पूर्ण उपवास रखें।' },
      { order: 4, title: 'Night Jagran', titleHi: 'रात्रि जागरण', description: 'Stay awake at night chanting Vishnu names and reading scriptures.', descHi: 'रात को जागकर विष्णु नाम जप और धर्मग्रंथ पठन करें।' },
      { order: 5, title: 'Parana', titleHi: 'पारणा', description: 'Break the fast on Dwadashi (twelfth day) after sunrise.', descHi: 'द्वादशी को सूर्योदय के बाद व्रत का पारणा करें।' },
    ],
    samagri: [
      { name: 'Tulsi leaves', nameHi: 'तुलसी के पत्ते', quantity: '21' },
      { name: 'Yellow flowers', nameHi: 'पीले फूल', quantity: '1 bunch' },
      { name: 'Incense sticks', nameHi: 'अगरबत्ती', quantity: '1 pack' },
      { name: 'Ghee lamp', nameHi: 'घी का दीपक', quantity: '1' },
      { name: 'Fruits (for fasting food)', nameHi: 'फल', quantity: 'as needed' },
    ],
  },
  {
    slug: 'pradosh-vrat',
    name: 'Pradosh Vrat',
    nameHi: 'प्रदोष व्रत',
    description: 'Worship of Lord Shiva on the thirteenth day (Trayodashi) of each lunar fortnight.',
    category: 'monthly',
    tradition: 'south',
    isFree: false,
    durationMinutes: 40,
    steps: [
      { order: 1, title: 'Day Fast', titleHi: 'दिवस उपवास', description: 'Fast throughout the day, taking only water or fruit.', descHi: 'पूरे दिन केवल जल या फल लेते हुए उपवास रखें।' },
      { order: 2, title: 'Twilight Puja', titleHi: 'प्रदोष पूजा', description: 'Worship Shiva during the 1.5 hours spanning sunset (pradosh kala).', descHi: 'सूर्यास्त के 1.5 घंटे के दौरान (प्रदोष काल में) शिव पूजा करें।' },
      { order: 3, title: 'Abhishek', titleHi: 'अभिषेक', description: 'Bathe Shiva Linga with milk, honey, ghee, curd, and water.', descHi: 'शिवलिंग को दूध, शहद, घी, दही और जल से अभिषेक करें।' },
      { order: 4, title: 'Maha Mrityunjaya Japa', titleHi: 'महामृत्युंजय जप', description: 'Chant Maha Mrityunjaya mantra 108 times.', descHi: 'महामृत्युंजय मंत्र का 108 बार जप करें।' },
    ],
    samagri: [
      { name: 'Milk', nameHi: 'दूध', quantity: '500ml' },
      { name: 'Honey', nameHi: 'शहद', quantity: '50ml' },
      { name: 'Ghee', nameHi: 'घी', quantity: '50ml' },
      { name: 'Curd', nameHi: 'दही', quantity: '100ml' },
      { name: 'Bilva leaves', nameHi: 'बेलपत्र', quantity: '108' },
      { name: 'Rudraksha mala', nameHi: 'रुद्राक्ष माला', quantity: '1', optional: true },
    ],
  },
  {
    slug: 'makar-sankranti-puja',
    name: 'Makar Sankranti Puja',
    nameHi: 'मकर संक्रान्ति पूजा',
    description: 'Sun\'s transition into Capricorn — harvest festival with sun worship and sesame rituals.',
    category: 'seasonal',
    tradition: 'north',
    isFree: true,
    durationMinutes: 30,
    steps: [
      { order: 1, title: 'Sunrise Bath', titleHi: 'सूर्योदय स्नान', description: 'Take a bath at sunrise, ideally in a sacred river.', descHi: 'सूर्योदय पर, यथासंभव पवित्र नदी में स्नान करें।' },
      { order: 2, title: 'Surya Arghya', titleHi: 'सूर्य अर्घ्य', description: 'Offer water to the rising sun with sesame seeds and red flowers.', descHi: 'उगते सूर्य को तिल और लाल फूलों के साथ अर्घ्य दें।' },
      { order: 3, title: 'Til-Gur Dana', titleHi: 'तिल-गुड़ दान', description: 'Donate sesame and jaggery to the poor and Brahmins.', descHi: 'गरीबों और ब्राह्मणों को तिल और गुड़ का दान करें।' },
      { order: 4, title: 'Kite Flying', titleHi: 'पतंगबाजी', description: 'Fly kites as a celebration of the sun\'s northward journey.', descHi: 'सूर्य की उत्तरायण यात्रा के उत्सव में पतंग उड़ाएं।' },
    ],
    samagri: [
      { name: 'Sesame seeds', nameHi: 'तिल', quantity: '250g' },
      { name: 'Jaggery', nameHi: 'गुड़', quantity: '250g' },
      { name: 'Red flowers', nameHi: 'लाल फूल', quantity: '1 bunch' },
      { name: 'Water pot', nameHi: 'जल पात्र', quantity: '1' },
      { name: 'Tilkut (sesame sweet)', nameHi: 'तिलकुट', quantity: '500g', optional: true },
    ],
  },
  {
    slug: 'vasant-panchami',
    name: 'Vasant Panchami',
    nameHi: 'वसन्त पञ्चमी',
    description: 'Worship of Goddess Saraswati at the onset of spring — day of learning and arts.',
    category: 'seasonal',
    tradition: 'north',
    isFree: true,
    durationMinutes: 45,
    steps: [
      { order: 1, title: 'Saraswati Sthapana', titleHi: 'सरस्वती स्थापना', description: 'Place Saraswati idol or image with books, musical instruments and pens.', descHi: 'पुस्तकों, वाद्य यंत्रों और कलमों के साथ सरस्वती माँ की मूर्ति या चित्र स्थापित करें।' },
      { order: 2, title: 'Shodashopachar Puja', titleHi: 'षोडशोपचार पूजा', description: 'Offer 16 services to Goddess Saraswati with white flowers.', descHi: 'सफेद फूलों के साथ माँ सरस्वती को 16 उपचार अर्पित करें।' },
      { order: 3, title: 'Pustaka Puja', titleHi: 'पुस्तक पूजा', description: 'Worship books and instruments as manifestations of the Goddess.', descHi: 'पुस्तकों और उपकरणों की देवी स्वरूप पूजा करें।' },
      { order: 4, title: 'Vidyarambha', titleHi: 'विद्यारंभ', description: 'Begin a new subject of learning — auspicious day for first lessons.', descHi: 'किसी नए विषय का अध्ययन आरंभ करें — पहले पाठ के लिए शुभ दिन।' },
    ],
    samagri: [
      { name: 'White flowers (marigold or jasmine)', nameHi: 'सफेद फूल', quantity: '1 bunch' },
      { name: 'Yellow cloth', nameHi: 'पीला वस्त्र', quantity: '1' },
      { name: 'Sweets (yellow)', nameHi: 'पीली मिठाई', quantity: '500g' },
      { name: 'Books and pens', nameHi: 'पुस्तकें और कलम', quantity: 'as needed' },
      { name: 'Incense sticks', nameHi: 'अगरबत्ती', quantity: '1 pack' },
    ],
  },
  {
    slug: 'paryushana',
    name: 'Paryushana',
    nameHi: 'पर्युषण',
    description: 'Eight-day Jain festival of fasting, reflection, forgiveness, and self-purification.',
    category: 'festival',
    tradition: 'jain',
    isFree: false,
    durationMinutes: 60,
    steps: [
      { order: 1, title: 'Samvatsari Fast', titleHi: 'संवत्सरी उपवास', description: 'Observe a complete fast (nirjala) on the final day.', descHi: 'अंतिम दिन पूर्ण निर्जल उपवास रखें।' },
      { order: 2, title: 'Pratikraman', titleHi: 'प्रतिक्रमण', description: 'Perform evening confession and repentance ritual.', descHi: 'संध्याकालीन प्रतिक्रमण — पश्चाताप और क्षमायाचना की विधि करें।' },
      { order: 3, title: 'Michhami Dukkadam', titleHi: 'मिच्छामि दुक्कडम', description: 'Ask forgiveness from all living beings: "If I have offended you in any way, forgive me."', descHi: 'सभी जीवों से क्षमा मांगें: "मिच्छामि दुक्कडम।"' },
    ],
    samagri: [
      { name: 'Jain scriptures (Agamas)', nameHi: 'जैन आगम', quantity: '1' },
      { name: 'White cloth', nameHi: 'सफेद वस्त्र', quantity: '1' },
      { name: 'Water (for the fast)', nameHi: 'जल', quantity: 'as needed' },
    ],
  },
  {
    slug: 'gurpurab',
    name: 'Gurpurab',
    nameHi: 'ਗੁਰਪੁਰਬ',
    description: 'Sikh celebration of a Guru\'s birth or life event with ardas, kirtan, and langar.',
    category: 'festival',
    tradition: 'sikh',
    isFree: true,
    durationMinutes: 120,
    steps: [
      { order: 1, title: 'Akhand Path', titleHi: 'ਅਖੰਡ ਪਾਠ', description: 'Continuous reading of the Guru Granth Sahib Ji for 48 hours preceding the event.', descHi: '48 घंटे तक अखंड पाठ — गुरु ग्रंथ साहिब जी का निरंतर पाठ।' },
      { order: 2, title: 'Prabhat Pheri', titleHi: 'ਪ੍ਰਭਾਤ ਫੇਰੀ', description: 'Early morning procession through the neighbourhood singing hymns.', descHi: 'प्रातःकाल कीर्तन गाते हुए मोहल्ले में प्रभात फेरी।' },
      { order: 3, title: 'Ardas', titleHi: 'ਅਰਦਾਸ', description: 'Congregational prayer at the Gurdwara.', descHi: 'गुरुद्वारे में संगत की अरदास।' },
      { order: 4, title: 'Langar', titleHi: 'ਲੰਗਰ', description: 'Community kitchen serving free meals to all.', descHi: 'समुदाय रसोई — सभी के लिए निःशुल्क भोजन।' },
    ],
    samagri: [
      { name: 'Karah Prasad ingredients (wheat, ghee, sugar)', nameHi: 'कड़ाह प्रसाद सामग्री', quantity: 'as per congregation' },
      { name: 'Flowers for decoration', nameHi: 'सजावट के लिए फूल', quantity: 'as needed' },
    ],
  },
  {
    slug: 'shiva-abhishek',
    name: 'Shiva Abhishek',
    nameHi: 'शिव अभिषेक',
    description: 'Sacred bath of the Shiva Linga with five holy substances (Panchamrita) and Vedic chanting.',
    category: 'monthly',
    tradition: 'south',
    isFree: true,
    durationMinutes: 40,
    steps: [
      { order: 1, title: 'Sankalpa', titleHi: 'संकल्प', description: 'State your intention for the abhishek.', descHi: 'अभिषेक का संकल्प करें।' },
      { order: 2, title: 'Panchamrita Abhishek', titleHi: 'पंचामृत अभिषेक', description: 'Bathe the Shiva Linga with milk, curd, honey, ghee, and sugar water while chanting Shri Rudram.', descHi: 'श्री रुद्रम का पाठ करते हुए शिवलिंग को दूध, दही, शहद, घी और शर्करा जल से स्नान कराएं।' },
      { order: 3, title: 'Water Abhishek', titleHi: 'जल अभिषेक', description: 'Pour sacred water from the Ganga or copper vessel over the Linga.', descHi: 'गंगाजल या तांबे के पात्र से शिवलिंग पर जलाभिषेक करें।' },
      { order: 4, title: 'Bhasma and Vibhuti', titleHi: 'भस्म और विभूति', description: 'Apply sacred ash to the Linga and to your forehead.', descHi: 'शिवलिंग पर और अपने माथे पर पवित्र भस्म/विभूति लगाएं।' },
      { order: 5, title: 'Bilva Archana', titleHi: 'बेलपत्र अर्चना', description: 'Offer 108 bilva leaf triplets chanting "Namah Shivaya" for each.', descHi: 'प्रत्येक "नमः शिवाय" के साथ 108 बेलपत्र त्रिपुटी अर्पित करें।' },
    ],
    samagri: [
      { name: 'Milk', nameHi: 'दूध', quantity: '500ml' },
      { name: 'Curd', nameHi: 'दही', quantity: '200ml' },
      { name: 'Honey', nameHi: 'शहद', quantity: '50ml' },
      { name: 'Ghee', nameHi: 'घी', quantity: '50ml' },
      { name: 'Sugar', nameHi: 'चीनी', quantity: '50g' },
      { name: 'Bilva leaves', nameHi: 'बेलपत्र', quantity: '108 triplets' },
      { name: 'Vibhuti (sacred ash)', nameHi: 'विभूति', quantity: '1 packet' },
      { name: 'Rudraksha mala', nameHi: 'रुद्राक्ष माला', quantity: '1' },
    ],
  },
  {
    slug: 'satyanarayan-katha',
    name: 'Satyanarayan Katha',
    nameHi: 'सत्यनारायण कथा',
    description: 'Reading of Lord Vishnu\'s Satyanarayan story for blessings and fulfillment of wishes.',
    category: 'festival',
    tradition: 'north',
    isFree: true,
    durationMinutes: 120,
    steps: [
      { order: 1, title: 'Sankalpa and Ganesh Puja', titleHi: 'संकल्प और गणेश पूजा', description: 'Take the vow and begin with Ganesha worship.', descHi: 'संकल्प लें और गणेश पूजा से प्रारंभ करें।' },
      { order: 2, title: 'Kalash Sthapana', titleHi: 'कलश स्थापना', description: 'Establish the sacred pot as symbol of Lord Vishnu.', descHi: 'भगवान विष्णु के प्रतीक के रूप में पवित्र कलश स्थापित करें।' },
      { order: 3, title: 'Katha Patha', titleHi: 'कथा पाठ', description: 'Read all five chapters of the Satyanarayan Katha.', descHi: 'सत्यनारायण कथा के पांचों अध्यायों का पाठ करें।' },
      { order: 4, title: 'Aarti', titleHi: 'आरती', description: 'Perform Vishnu Aarti.', descHi: 'विष्णु आरती करें।' },
      { order: 5, title: 'Prasad Distribution', titleHi: 'प्रसाद वितरण', description: 'Distribute panchamrit and panjiri prasad to all.', descHi: 'सभी को पंचामृत और पंजीरी प्रसाद वितरित करें।' },
    ],
    samagri: [
      { name: 'Satyanarayan Katha book', nameHi: 'सत्यनारायण कथा पुस्तक', quantity: '1' },
      { name: 'Yellow cloth', nameHi: 'पीला वस्त्र', quantity: '2 pieces' },
      { name: 'Wheat flour', nameHi: 'गेहूं का आटा', quantity: '500g' },
      { name: 'Sugar', nameHi: 'चीनी', quantity: '250g' },
      { name: 'Ghee', nameHi: 'घी', quantity: '250g' },
      { name: 'Fruits and dry fruits', nameHi: 'फल और मेवे', quantity: '1kg' },
      { name: 'Panchamrit ingredients', nameHi: 'पंचामृत सामग्री', quantity: '1 set' },
      { name: 'Tulsi leaves', nameHi: 'तुलसी के पत्ते', quantity: '21' },
    ],
  },
  {
    slug: 'griha-pravesh',
    name: 'Griha Pravesh',
    nameHi: 'गृह प्रवेश',
    description: 'Housewarming ceremony to purify and consecrate a new home before moving in.',
    category: 'lifecycle',
    tradition: 'north',
    isFree: true,
    durationMinutes: 90,
    steps: [
      { order: 1, title: 'Vastu Puja', titleHi: 'वास्तु पूजा', description: 'Worship Vastu Purusha (deity of directions) to sanctify the space.', descHi: 'वास्तु पुरुष (दिशाओं के देवता) की पूजा कर स्थान को पवित्र करें।' },
      { order: 2, title: 'Navagraha Puja', titleHi: 'नवग्रह पूजा', description: 'Worship nine planets for protection and prosperity in the home.', descHi: 'घर में सुरक्षा और समृद्धि के लिए नवग्रह पूजा करें।' },
      { order: 3, title: 'Havan', titleHi: 'हवन', description: 'Perform fire ceremony to purify the home\'s atmosphere.', descHi: 'घर के वातावरण को शुद्ध करने के लिए हवन करें।' },
      { order: 4, title: 'Threshold Crossing', titleHi: 'देहली पूजन', description: 'Owner enters home with right foot first, wife follows overturning rice with her toe.', descHi: 'गृहस्वामी दाहिने पैर से पहले प्रवेश करें, पत्नी पैर के अंगूठे से चावल उलटते हुए प्रवेश करें।' },
      { order: 5, title: 'Boiling Milk', titleHi: 'दूध उबालना', description: 'Boil milk on the new hearth until it overflows — symbolises abundance.', descHi: 'नए चूल्हे पर दूध उबालें जब तक उफान न आए — यह समृद्धि का प्रतीक है।' },
    ],
    samagri: [
      { name: 'Havan kund', nameHi: 'हवन कुंड', quantity: '1' },
      { name: 'Havan samagri', nameHi: 'हवन सामग्री', quantity: '500g' },
      { name: 'Mango wood', nameHi: 'आम की लकड़ी', quantity: '2kg' },
      { name: 'Ghee', nameHi: 'घी', quantity: '500g' },
      { name: 'Rice', nameHi: 'चावल', quantity: '1kg' },
      { name: 'Milk', nameHi: 'दूध', quantity: '1 litre' },
      { name: 'Red cloth', nameHi: 'लाल वस्त्र', quantity: '1' },
      { name: 'Coconut', nameHi: 'नारियल', quantity: '3' },
    ],
  },
  {
    slug: 'upanayana-janeu',
    name: 'Upanayana (Janeu Ceremony)',
    nameHi: 'उपनयन संस्कार (जनेऊ)',
    description: 'Sacred thread ceremony marking a boy\'s spiritual second birth and entry into student life.',
    category: 'lifecycle',
    tradition: 'south',
    isFree: false,
    durationMinutes: 180,
    steps: [
      { order: 1, title: 'Keshanta (head shaving)', titleHi: 'केशान्त (मुंडन)', description: 'The boy\'s head is shaved leaving only a tuft (shikha).', descHi: 'बालक के सिर का मुंडन, केवल शिखा छोड़कर।' },
      { order: 2, title: 'Homa', titleHi: 'होम', description: 'Fire ceremony to mark the new beginning.', descHi: 'नए आरंभ को चिह्नित करने के लिए अग्नि होम।' },
      { order: 3, title: 'Mekhala (girding)', titleHi: 'मेखला धारण', description: 'Tie a grass cord (mekhala) around the boy\'s waist.', descHi: 'बालक की कमर में कुशा की मेखला बांधें।' },
      { order: 4, title: 'Yajnopavita Dharana', titleHi: 'यज्ञोपवीत धारण', description: 'Guru places the sacred thread over the boy\'s left shoulder.', descHi: 'गुरु बालक के बाएं कंधे पर पवित्र जनेऊ धारण कराते हैं।' },
      { order: 5, title: 'Gayatri Upadesh', titleHi: 'गायत्री उपदेश', description: 'Guru whispers the Gayatri Mantra into the boy\'s right ear for the first time.', descHi: 'गुरु पहली बार बालक के दाहिने कान में गायत्री मंत्र का उपदेश देते हैं।' },
      { order: 6, title: 'Bhiksha (begging alms)', titleHi: 'भिक्षाटन', description: 'Boy goes to mother and relatives asking for alms as a symbolic student.', descHi: 'बालक माँ और परिजनों से प्रतीकात्मक रूप से भिक्षा माँगता है।' },
    ],
    samagri: [
      { name: 'Sacred thread (yajnopavita)', nameHi: 'जनेऊ', quantity: '3 strands' },
      { name: 'Deer skin or yellow cloth', nameHi: 'मृगचर्म या पीला वस्त्र', quantity: '1' },
      { name: 'Havan kund and samagri', nameHi: 'हवन कुंड और सामग्री', quantity: '1 set' },
      { name: 'Danda (staff)', nameHi: 'दण्ड', quantity: '1' },
      { name: 'Ghee', nameHi: 'घी', quantity: '500g' },
      { name: 'Kusha grass', nameHi: 'कुशा घास', quantity: '1 bundle' },
    ],
  },
  {
    slug: 'shraddha-pitru-puja',
    name: 'Shraddha (Pitru Puja)',
    nameHi: 'श्राद्ध (पितृ पूजा)',
    description: 'Annual ancestral rites performed during Pitru Paksha to honour and liberate departed souls.',
    category: 'seasonal',
    tradition: 'north',
    isFree: false,
    durationMinutes: 90,
    steps: [
      { order: 1, title: 'Sankalpa', titleHi: 'संकल्प', description: 'State the names of ancestors for whom shraddha is being performed.', descHi: 'जिन पितरों के लिए श्राद्ध किया जा रहा है उनके नाम का संकल्प करें।' },
      { order: 2, title: 'Pinda Daan', titleHi: 'पिंड दान', description: 'Offer rice balls (pindas) to the ancestors at a river bank or at home.', descHi: 'नदी किनारे या घर पर पितरों को चावल के पिंड दान करें।' },
      { order: 3, title: 'Tarpan', titleHi: 'तर्पण', description: 'Pour water mixed with sesame seeds, barley, and kusha grass for each ancestor.', descHi: 'प्रत्येक पितर के लिए तिल, जौ और कुशा मिश्रित जल का तर्पण करें।' },
      { order: 4, title: 'Brahmin Bhojan', titleHi: 'ब्राह्मण भोजन', description: 'Feed Brahmins who represent the ancestors.', descHi: 'पितरों के प्रतिनिधि के रूप में ब्राह्मणों को भोजन कराएं।' },
      { order: 5, title: 'Cow and Crow Feeding', titleHi: 'गाय और कौए को भोजन', description: 'Offer food to a cow and crow — both are said to carry the food to ancestors.', descHi: 'गाय और कौए को भोजन दें — दोनों पितरों तक भोजन पहुंचाते हैं।' },
    ],
    samagri: [
      { name: 'Rice (cooked)', nameHi: 'पका चावल', quantity: '500g' },
      { name: 'Sesame seeds (black)', nameHi: 'काले तिल', quantity: '100g' },
      { name: 'Barley (jau)', nameHi: 'जौ', quantity: '100g' },
      { name: 'Kusha grass', nameHi: 'कुशा घास', quantity: '1 bundle' },
      { name: 'Banana leaf or plate', nameHi: 'केले का पत्ता या थाली', quantity: '1' },
      { name: 'Water pot', nameHi: 'जल पात्र', quantity: '1' },
      { name: 'Cow milk sweets', nameHi: 'गाय के दूध की मिठाई', quantity: '500g' },
    ],
  },
  {
    slug: 'durga-puja-saptami',
    name: 'Durga Puja (Saptami)',
    nameHi: 'दुर्गा पूजा (सप्तमी)',
    description: 'Grand worship of Goddess Durga on the seventh day of Navratri with 108-name chanting.',
    category: 'festival',
    tradition: 'east',
    isFree: false,
    durationMinutes: 120,
    steps: [
      { order: 1, title: 'Nabapatrika Snan', titleHi: 'नवपत्रिका स्नान', description: 'Bathe the nine-plant cluster (nabapatrika) representing Durga\'s nine forms.', descHi: 'नौ पौधों के गुच्छ (नवपत्रिका) को दुर्गा के नौ रूपों के प्रतीक रूप में स्नान कराएं।' },
      { order: 2, title: 'Prana Pratishtha', titleHi: 'प्राण प्रतिष्ठा', description: 'Invoke the Goddess into the idol with mantras and ritual eye-opening.', descHi: 'मंत्रों और नयन-उन्मीलन विधि से मूर्ति में देवी का आवाहन करें।' },
      { order: 3, title: 'Shodash Upachar', titleHi: 'षोडश उपचार', description: 'Offer 16 services including the Durga Saptashati recitation.', descHi: 'दुर्गा सप्तशती पाठ सहित 16 उपचार अर्पित करें।' },
      { order: 4, title: 'Dhunuchi Naach', titleHi: 'धुनुची नृत्य', description: 'Devotees dance with clay pots of burning coconut husk and incense.', descHi: 'भक्त जलते नारियल की भूसी और धूप से भरे मिट्टी के घड़े लेकर नृत्य करते हैं।' },
      { order: 5, title: 'Sindoor Khela', titleHi: 'सिंदूर खेला', description: 'Married women apply vermilion to the Goddess and to each other.', descHi: 'विवाहित महिलाएं देवी को और एक-दूसरे को सिंदूर लगाती हैं।' },
    ],
    samagri: [
      { name: 'Durga idol (clay)', nameHi: 'मिट्टी की दुर्गा मूर्ति', quantity: '1' },
      { name: 'Red hibiscus flowers', nameHi: 'लाल गुड़हल के फूल', quantity: '108' },
      { name: 'Nabapatrika (9 plants)', nameHi: 'नवपत्रिका', quantity: '1 bundle' },
      { name: 'Sindoor', nameHi: 'सिंदूर', quantity: '100g' },
      { name: 'Dhunuchi (clay censer)', nameHi: 'धुनुची', quantity: '2' },
      { name: 'Coconut husk and incense', nameHi: 'नारियल की भूसी और धूप', quantity: 'as needed' },
      { name: 'Durga Saptashati book', nameHi: 'दुर्गा सप्तशती पुस्तक', quantity: '1' },
    ],
  },
  {
    slug: 'tulsi-vivah',
    name: 'Tulsi Vivah',
    nameHi: 'तुलसी विवाह',
    description: 'Ceremonial marriage of Tulsi plant (Goddess Vrinda) with Lord Vishnu (Shaligram) marking the end of the chaturmas period.',
    category: 'seasonal',
    tradition: 'north',
    isFree: true,
    durationMinutes: 60,
    steps: [
      { order: 1, title: 'Tulsi Sringaar', titleHi: 'तुलसी श्रृंगार', description: 'Adorn the Tulsi plant with new clothes, jewellery and a veil made of sugarcane.', descHi: 'तुलसी पौधे को नए वस्त्र, आभूषण और गन्ने का घूंघट पहनाएं।' },
      { order: 2, title: 'Mandap Decoration', titleHi: 'मंडप सजावट', description: 'Create a wedding canopy around the Tulsi pot with banana stems and mango leaves.', descHi: 'केले के तने और आम के पत्तों से तुलसी के गमले के चारों ओर विवाह मंडप सजाएं।' },
      { order: 3, title: 'Shaligram Sthapana', titleHi: 'शालिग्राम स्थापना', description: 'Place the Shaligram (Vishnu\'s stone form) beside the Tulsi.', descHi: 'तुलसी के पास शालिग्राम (विष्णु का पत्थर रूप) स्थापित करें।' },
      { order: 4, title: 'Vivah Mantra', titleHi: 'विवाह मंत्र', description: 'Chant wedding mantras and perform the symbolic seven circumambulations.', descHi: 'विवाह मंत्र पढ़ें और प्रतीकात्मक सप्तपदी करें।' },
      { order: 5, title: 'Aarti and Prasad', titleHi: 'आरती और प्रसाद', description: 'Perform aarti and distribute sweets as prasad.', descHi: 'आरती करें और मिठाई प्रसाद वितरित करें।' },
    ],
    samagri: [
      { name: 'Tulsi plant in pot', nameHi: 'गमले में तुलसी पौधा', quantity: '1' },
      { name: 'Shaligram stone', nameHi: 'शालिग्राम', quantity: '1' },
      { name: 'Sugarcane stalks', nameHi: 'गन्ने के डंठल', quantity: '4' },
      { name: 'Banana stems', nameHi: 'केले के तने', quantity: '4' },
      { name: 'Small red cloth (for Tulsi)', nameHi: 'तुलसी के लिए लाल वस्त्र', quantity: '1' },
      { name: 'Amla (Indian gooseberry)', nameHi: 'आंवला', quantity: '21' },
      { name: 'Sweets', nameHi: 'मिठाई', quantity: '500g' },
    ],
  },
];

async function main() {
  console.log('Seeding database...');

  for (const ritual of rituals) {
    const { steps, samagri, ...ritualData } = ritual;

    await prisma.ritual.upsert({
      where: { slug: ritual.slug },
      update: {},
      create: {
        ...ritualData,
        steps: { create: steps },
        samagri: { create: samagri },
      },
    });

    console.log(`  ✓ ${ritual.name}`);
  }

  console.log(`Seeding complete. ${rituals.length} rituals seeded.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
